In [1]:
import numpy as np

In [2]:
v = np.array([1,-1,2])
w = np.array([2,5,2])

In [3]:
v+w

array([3, 4, 4])

In [4]:
v-w

array([-1, -6,  0])

In [5]:
print(3*v)

[ 3 -3  6]


In [7]:
print(np.linalg.norm(v)) #prints the length of vector

2.449489742783178


In [8]:
s = np.dot(v,w)

In [9]:
s

1