In [1]:
import numpy as np

In [2]:
A = np.array([[1,7],[2,1],[3,2]])

In [3]:
print(A)

[[1 7]
 [2 1]
 [3 2]]


In [5]:
B = np.array([[1,1],[1,-1],[1,0]])

In [6]:
print(B)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [9]:
add = np.add(A,B)
add

array([[2, 8],
       [3, 0],
       [4, 2]])

In [10]:
sub = np.subtract(A,B)
sub

array([[0, 6],
       [1, 2],
       [2, 2]])

In [11]:
P = np.array([[1,3,1],[1,0,1]])

In [12]:
P

array([[1, 3, 1],
       [1, 0, 1]])

In [21]:
S = np.dot(A,P)

In [22]:
S

array([[8, 3, 8],
       [3, 6, 3],
       [5, 9, 5]])

In [23]:
detm = np.linalg.det(S)

In [24]:
detm

0.0

In [26]:
inv = np.linalg.inv(S) #inverse of S doesn't exist

LinAlgError: Singular matrix

In [27]:
m = np.array([[1,-1],[2,3]])

In [28]:
print(np.linalg.inv(m))

[[ 0.6  0.2]
 [-0.4  0.2]]
