In [1]:
import numpy as np

In [2]:
A = np.array([[2,-2,3],[1,1,1],[1,3,-1]])

In [3]:
A

array([[ 2, -2,  3],
       [ 1,  1,  1],
       [ 1,  3, -1]])

In [4]:
#calculate eigen values and eigen vectors

In [5]:
values , vectors = np.linalg.eig(A)

In [7]:
print(values)

[ 3.  1. -2.]


In [8]:
print(vectors)

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [13]:
B = np.array([[2,0,0],[0,1,0],[0,0,-1]])

In [14]:
B

array([[ 2,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [15]:
values , vectors = np.linalg.eig(B)

In [16]:
print(values)

[ 2.  1. -1.]


In [17]:
print(vectors)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
