In [1]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

In [2]:
a = np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])

In [3]:
a

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [0, 1, 1, 0]])

In [4]:
u, s, vh = np.linalg.svd(a, full_matrices=True)

In [5]:
u

array([[ 0.8109, -0.0934,  0.5776],
       [ 0.57  ,  0.3493, -0.7437],
       [ 0.1323, -0.9324, -0.3365]])

In [6]:
vh

array([[ 0.2046,  0.3443,  0.5488,  0.7338],
       [ 0.2181, -0.6561, -0.438 ,  0.5746],
       [-0.7598,  0.3431, -0.4167,  0.3625],
       [-0.5774, -0.5774,  0.5774,  0.    ]])

In [23]:
s=[6.7509, 1.1734, 0]

In [8]:
u.shape, s.shape, vh.shape

((3, 3), (3,), (4, 4))

In [11]:
#####################################################################

In [24]:
sd = np.diag(s)
sd

array([[6.7509, 0.    , 0.    ],
       [0.    , 1.1734, 0.    ],
       [0.    , 0.    , 0.    ]])

In [13]:
sd.shape

(3, 3)

In [14]:
b = np.zeros((3,4))

In [15]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
b[:,:-1]=sd

In [26]:
sigma = b
sigma

array([[6.7509, 0.    , 0.    , 0.    ],
       [0.    , 1.1734, 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    ]])

In [27]:
print(np.dot(np.dot(u,sigma),vh))

[[ 1.0959  1.9567  3.0526  3.9542]
 [ 0.8764  1.0558  1.9322  3.0589]
 [-0.0559  1.0252  0.9693  0.0267]]


In [29]:
##################-----EXAMPLE-2------#######################

In [30]:
a = np.array([[1,2,3,4], [1,1,2,3], [0,1,1,0], [0,2,2,0], [0,5,5,0]])

In [31]:
a

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [0, 1, 1, 0],
       [0, 2, 2, 0],
       [0, 5, 5, 0]])

In [32]:
u, s, vh = np.linalg.svd(a)

In [33]:
u 

array([[-0.5185, -0.5983,  0.6108, -0.    , -0.    ],
       [-0.3389, -0.512 , -0.7893,  0.    ,  0.    ],
       [-0.1433,  0.1125, -0.0114, -0.4103, -0.8935],
       [-0.2866,  0.225 , -0.0229, -0.8155,  0.4491],
       [-0.7166,  0.5626, -0.0572,  0.4082, -0.001 ]])

In [34]:
s

array([9.2296, 4.4454, 0.2312, 0.    ])

In [35]:
vh

array([[-0.0929, -0.6149, -0.7079, -0.3349],
       [-0.2498,  0.375 ,  0.1252, -0.8839],
       [-0.7718,  0.3846, -0.3872,  0.3264],
       [ 0.5774,  0.5774, -0.5774,  0.    ]])